// © 2026 Martín Viera. Todos los derechos reservados.

// MV Kobra AI · Guiones de las demos animadas, en los tres idiomas del producto.
//
// Antes vivían escritos a mano dentro de index.html, solo en castellano: elegir
// portugués o inglés en el sitio no cambiaba nada de la llamada ni del chat.
//
// Es un .js y no un .json a propósito: el demo offline se abre con doble clic
// (protocolo file://), donde `fetch` de un archivo local está bloqueado por
// CORS. Un <script> se carga siempre.
//
// Formato estricto `window.GUIONES = {...};` — `data/generar_audio_demo_voz.py`
// lee este mismo archivo para sintetizar el audio, así que texto en pantalla y
// audio no se pueden desincronizar.
//
// Sobre la moneda: los importes quedan en pesos en los tres idiomas porque el
// tablero que se ve al lado muestra la cartera sintética en pesos uruguayos.
// Traducir la moneda en el guion y no en los datos dejaría la demo incoherente.
window.GUIONES = {
  "es": {
    "nombre": "Español",
    "llamada": [
      {"who": "ia", "text": "Buenos días, hablo de MV Kobra AI en representación de su entidad financiera. ¿Hablo con Juan Pérez?"},
      {"who": "cliente", "text": "Sí, soy yo."},
      {"who": "ia", "text": "Lo contacto por un saldo pendiente de 6.000 pesos con más de 60 días de atraso. ¿Podemos revisar juntos las opciones de pago disponibles?"},
      {"who": "cliente", "text": "La verdad ahora no puedo pagar todo junto, estoy complicado económicamente."},
      {"who": "ia", "text": "Entiendo la situación. Puedo ofrecerle cancelar hoy con un 5% de descuento, quedando en 5.700 pesos, o dividirlo en 3 cuotas de 1.900 pesos sin recargo. ¿Cuál se ajusta mejor a su situación?"},
      {"who": "cliente", "text": "Prefiero las 3 cuotas."},
      {"who": "ia", "text": "Perfecto. Le voy a enviar por WhatsApp el link de pago de la primera cuota, con vencimiento en 5 días. ¿Confirma este número para el envío?"},
      {"who": "cliente", "text": "Sí, confirmo."},
      {"who": "ia", "text": "Excelente. Quedó registrado el acuerdo de pago en 3 cuotas. Muchas gracias por su tiempo, que tenga un buen día."}
    ],
    "whatsapp": [
      {"who": "ia", "text": "Hola Juan Soy el asistente de cobranzas de su entidad financiera. Tiene un saldo pendiente de $U 6.000 con más de 60 días de atraso. ¿Quiere que veamos opciones para regularizarlo?"},
      {"who": "cliente", "text": "Hola, sí. Ahora no puedo pagar todo junto."},
      {"who": "ia", "text": "No hay problema. Puedo ofrecerle: 1) Pagar hoy $U 5.700 (5% de descuento), o 2) 3 cuotas de $U 1.900 sin recargo. ¿Cuál prefiere?"},
      {"who": "cliente", "text": "Las 3 cuotas, por favor."},
      {"who": "ia", "text": "Perfecto ✓ Le comparto el link de pago de la primera cuota: kobra.pay/ab12c9 — vence en 5 días."},
      {"who": "cliente", "text": "Listo, muchas gracias."}
    ],
    "ui": {
      "etiqueta_ia": "MV Kobra AI (voz)",
      "etiqueta_cliente": "Cliente",
      "en_curso_voz": "Llamada en curso (voz real)…",
      "en_curso_nav": "Llamada en curso (con voz)…",
      "en_curso": "Llamada en curso…",
      "detenida": "⏹ Detenida",
      "finalizada": "✓ Llamada finalizada · Duración 00:42 · Acuerdo de pago en 3 cuotas · sincronizado al ERP",
      "idioma": "Idioma",
      "badge": "Cobranzas Inteligentes",
      "header_sub": "ProbPago · Agente IA Negociador · Priorización por valor esperado de recupero",
      "cinta": "Demo pública · datos sintéticos · ver planes",
      "pie": "MV Kobra AI · Plataforma de Cobranzas Inteligentes · Demo con datos sintéticos (Uruguay). Sin nombres de clientes.",
      "f_segmento": "Segmento",
      "f_producto": "Producto",
      "f_tramo_mora": "Tramo de mora",
      "f_propension": "Propensión",
      "f_departamento": "Departamento",
      "f_todos": "Todos",
      "f_prob_min": "ProbPago mínima:",
      "prop_Alta": "Alta",
      "prop_Media": "Media",
      "prop_Baja": "Baja",
      "kpi_deudores": "Deudores",
      "kpi_cartera": "Cartera (UYU)",
      "kpi_recupero": "Recupero esp. ({p}%)",
      "kpi_probpago": "ProbPago promedio",
      "kpi_mora": "Mora promedio",
      "kpi_riesgo": "Cartera en riesgo",
      "dias": "días",
      "g_tramo": "Cartera vs. recupero esperado por tramo de mora (M$U)",
      "g_prop": "Distribución por propensión de pago",
      "g_seg": "Recupero esperado por segmento (UYU)",
      "g_est": "Recupero esperado por estrategia (UYU)",
      "ds_cartera": "Cartera",
      "ds_recupero_esp": "Recupero esperado",
      "ds_recupero": "Recupero",
      "t_titulo": "Cartera priorizada",
      "btn_csv": "Exportar CSV",
      "btn_excel": "Exportar Excel",
      "th_num": "#",
      "th_id": "ID",
      "th_segmento": "Segmento",
      "th_producto": "Producto",
      "th_depto": "Depto",
      "th_tramo": "Tramo",
      "th_monto": "Monto",
      "th_probpago": "ProbPago",
      "th_prop": "Prop.",
      "th_estrategia": "Estrategia",
      "th_desc": "Desc.",
      "th_canal": "Canal",
      "th_recupero": "Recupero esp.",
      "t_info": "{n} registros filtrados · mostrando top 300 por prioridad",
      "mc_titulo": "Probalo con tu cartera",
      "mc_texto": "Subí un CSV anonimizado —500 cuentas alcanzan— y mirá el scoring corriendo sobre <b>tus</b> números. <b>El archivo no sale de tu navegador</b>: se lee y se scorea acá, no se sube a ningún servidor. Es el mismo modelo que ves arriba, no una versión de demostración: los coeficientes salen del <code>.joblib</code> entrenado.",
      "mc_elegir": "Elegir CSV",
      "mc_bajar": "⬇ Bajar un CSV de ejemplo (500 cuentas)",
      "mc_leyendo": "Leyendo {archivo}…",
      "mc_pesado": "Ese archivo pesa {mb} MB. Probá con una muestra de unas miles de filas: para ver el scoring alcanza.",
      "mc_no_lee": "No pude leer el archivo.",
      "mc_no_modelo": "No pude cargar el modelo ({e}). Recargá la página.",
      "mc_sin_filas": "El archivo no tiene filas de datos. ¿Le quedó solo el encabezado?",
      "mc_faltan": "<b>Le faltan {n} columna(s) al archivo.</b><br>El modelo necesita: <code>{pedidas}</code>.<br>No encontré: <code>{faltan}</code>.<br>Bajá el CSV de ejemplo de arriba para ver el formato exacto — los nombres no distinguen mayúsculas.",
      "mc_k_cuentas": "Cuentas scoreadas",
      "mc_k_prob": "ProbPago promedio",
      "mc_k_recupero": "Recupero esperado",
      "mc_k_altabaja": "Alta / baja propensión",
      "mc_resumen": "{archivo} · {n} filas en {ms} ms, en tu navegador. Cartera {cartera}.",
      "mc_top": "Top 15 por valor esperado de recupero",
      "mc_th_cuenta": "Cuenta",
      "mc_th_monto": "Monto",
      "mc_th_recupero": "Recupero esperado",
      "mc_th_prop": "Propensión",
      "mc_pie": "El modelo está entrenado con datos <b>sintéticos</b>: esto muestra la mecánica del scoring y la priorización. El desempeño real se mide reentrenando con tu histórico de pagos.",
      "v_titulo": "Gestor IA por voz",
      "v_sub": "Así llama y negocia MV Kobra AI por teléfono, con voz sintetizada en vivo (subí el volumen).",
      "v_btn": "▶ Reproducir llamada de ejemplo (con voz)",
      "v_stop": "⏹ Detener",
      "w_titulo": "Negociador por WhatsApp",
      "w_sub": "El mismo agente cierra por chat, manda el link de pago y registra todo solo.",
      "w_btn": "▶ Reproducir conversación de ejemplo",
      "w_escribiendo": "Escribiendo…",
      "c_titulo": "Copiloto de Negociación",
      "c_hint": "Pegá una conversación (WhatsApp o transcripción). Analizala <b>offline</b> en tu navegador, o con <b>IA en vivo</b> (motor neuronal real).",
      "c_btn_offline": "⚡ Analizar offline",
      "c_btn_ia": "Analizar con IA en vivo",
      "c_sentimiento": "Sentimiento del cliente turno a turno",
      "c_emociones": "Emociones:",
      "c_tecnicas": "Técnicas del gestor:",
      "c_k_calidad": "Calidad de gestión",
      "c_k_clima": "Clima del cliente",
      "c_k_emocion": "Emoción dominante",
      "c_k_tecnicas": "Técnicas usadas",
      "c_proxima": "Próxima frase sugerida",
      "c_turnos": "{n} turnos analizados",
      "c_pega": "Pegá una conversación.",
      "c_pega_primero": "Pegá una conversación primero.",
      "ia_consultando": "Consultando a la IA…",
      "ia_titulo": "Análisis de IA (en vivo)",
      "ia_temp": "Temperatura del cliente",
      "ia_tecnicas": "Técnicas detectadas:",
      "ia_jugada": "Próxima jugada:",
      "ia_guion": "Guion sugerido:",
      "ia_nokey": "La IA en vivo todavía no está configurada (falta la API key en el servidor).",
      "ia_limit": "Se agotaron las demos de IA en vivo gratis. Escribinos a vieraschiavi@gmail.com para ampliar.",
      "ia_error": "No se pudo analizar en vivo ({e}).",
      "ia_sin_conexion": "Sin conexión con la IA: {e}",
      "ia_restantes": "IA en vivo: quedan {n} demos gratis (global)",
      "e_titulo": "Resultados enviados a tu ERP",
      "e_sub": "Cada gestión cerrada (voz, WhatsApp o copiloto) se sincroniza sola a tu ERP o base de datos — por API REST, SQL o archivo. Así se ve del otro lado:",
      "e_evolucion": "Evolución de recupero (últimos 30 días)",
      "e_mismo_dato": "Mismo dato que recibe tu ERP vía API/SQL",
      "e_k_cerradas": "Gestiones cerradas",
      "e_k_sync": "Sincronizadas al ERP",
      "e_k_pend": "Pendientes de sync",
      "e_k_recuperado": "Recuperado (30 días)",
      "e_ds_recuperado": "Recuperado (UYU)",
      "e_th_fecha": "Fecha",
      "e_th_cliente": "Cliente",
      "e_th_canal": "Canal",
      "e_th_resultado": "Resultado",
      "e_th_monto": "Monto",
      "e_th_estado": "Estado ERP",
      "e_sincronizado": "Sincronizado",
      "e_pendiente": "Pendiente",
      "e_r_promesa": "Promesa de pago",
      "e_r_acuerdo": "Acuerdo en cuotas",
      "e_r_pago": "Pago total",
      "e_r_sin_contacto": "Sin contacto",
      "e_c_voz": "Voz IA",
      "e_c_whatsapp": "WhatsApp",
      "e_c_copiloto": "Copiloto",
      "cop_enojo_t": "Cliente enojado",
      "cop_enojo_d": "Bajá el ritmo, validá su malestar ANTES de ofrecer. Evitá justificar.",
      "cop_frustracion_t": "Frustración",
      "cop_frustracion_d": "Reconocé el historial y ofrecé algo concreto y distinto a lo anterior.",
      "cop_ansiedad_t": "Ansiedad",
      "cop_ansiedad_d": "Transmití calma y pasos claros y cortos: 'hagamos una sola cosa hoy'.",
      "cop_dificultad_t": "Dificultad económica",
      "cop_dificultad_d": "Priorizá plan de cuotas o quita; no presiones el pago total.",
      "cop_compra_t": "Señal de compra",
      "cop_compra_d": "Clima favorable: CERRÁ ahora con fecha y medio de pago.",
      "cop_objecion_t": "Objeción activa",
      "cop_objecion_d": "No rebatas de frente: '¿qué parte le complica?' y ofrecé 2 alternativas.",
      "cop_alta_t": "Alta propensión",
      "cop_alta_d": "Apuntá a pago total o cuota inicial fuerte; poca o nula quita.",
      "cop_baja_t": "Baja propensión",
      "cop_baja_d": "Asegurá CUALQUIER pago: habilitá quita/plan largo y compromiso escrito.",
      "cop_estrategia_t": "Estrategia sugerida",
      "cop_estrategia_d": "Guion recomendado por MV Kobra AI: «{e}».",
      "cop_ok_t": "Todo en orden",
      "cop_ok_d": "Mantené el tono y avanzá hacia el cierre con una propuesta concreta.",
      "cop_next_cierre": "Perfecto, coordinemos: le envío ahora el link de pago y le llega el comprobante. ¿Le queda cómodo?",
      "cop_next_enojo": "Entiendo su molestia y quiero resolverlo hoy mismo. Le propongo una opción hecha a su medida, ¿la vemos?",
      "cop_next_dificultad": "Sin problema, busquemos algo acorde a su situación. ¿Cuánto podría afrontar este mes?",
      "cop_next_default": "¿Qué le parece si lo dividimos en cuotas cómodas y arrancamos con una hoy?",
      "clima_positivo": "positivo",
      "clima_neutro": "neutro",
      "clima_negativo": "negativo",
      "emo_enojo": "enojo",
      "emo_frustracion": "frustración",
      "emo_ansiedad": "ansiedad",
      "emo_dificultad_economica": "dificultad económica",
      "emo_intencion_pago": "intención de pago",
      "emo_objecion": "objeción",
      "d_Corporativo": "Corporativo",
      "d_Pyme": "Pyme",
      "d_Retail": "Retail",
      "d_Crédito automotor": "Crédito automotor",
      "d_Cuenta corriente": "Cuenta corriente",
      "d_Financiación retail": "Financiación retail",
      "d_Microcrédito": "Microcrédito",
      "d_Préstamo personal": "Préstamo personal",
      "d_Tarjeta de crédito": "Tarjeta de crédito",
      "d_Derivación a gestión especializada": "Derivación a gestión especializada",
      "d_Descuento máximo / cierre de cuenta": "Descuento máximo / cierre de cuenta",
      "d_Pago total facilitado": "Pago total facilitado",
      "d_Plan de cuotas": "Plan de cuotas",
      "d_Plan de cuotas + quita moderada": "Plan de cuotas + quita moderada",
      "d_Quita agresiva por pago único": "Quita agresiva por pago único",
      "d_Recordatorio suave": "Recordatorio suave",
      "d_Email": "Email",
      "d_Llamada": "Llamada",
      "d_SMS": "SMS",
      "d_WhatsApp": "WhatsApp",
      "modelo_logistica": "Regresión Logística (seleccionada por CV + calibrada)",
      "lift_decil": "decil 10",
      "e_doc_titulo": "MV Kobra AI · Resultados enviados a ERP"
    }
  },
  "pt": {
    "nombre": "Português",
    "llamada": [
      {"who": "ia", "text": "Bom dia, falo da MV Kobra AI em nome da sua instituição financeira. Falo com João Pereira?"},
      {"who": "cliente", "text": "Sim, sou eu."},
      {"who": "ia", "text": "Estou entrando em contato por um saldo pendente de 6.000 pesos com mais de 60 dias de atraso. Podemos ver juntos as opções de pagamento disponíveis?"},
      {"who": "cliente", "text": "Na verdade, agora não consigo pagar tudo de uma vez, estou apertado financeiramente."},
      {"who": "ia", "text": "Entendo a situação. Posso oferecer quitar hoje com 5% de desconto, ficando em 5.700 pesos, ou dividir em 3 parcelas de 1.900 pesos sem juros. Qual se encaixa melhor na sua situação?"},
      {"who": "cliente", "text": "Prefiro as 3 parcelas."},
      {"who": "ia", "text": "Perfeito. Vou enviar pelo WhatsApp o link de pagamento da primeira parcela, com vencimento em 5 dias. Confirma este número para o envio?"},
      {"who": "cliente", "text": "Sim, confirmo."},
      {"who": "ia", "text": "Excelente. O acordo de pagamento em 3 parcelas ficou registrado. Muito obrigado pelo seu tempo, tenha um bom dia."}
    ],
    "whatsapp": [
      {"who": "ia", "text": "Olá João Sou o assistente de cobrança da sua instituição financeira. Você tem um saldo pendente de $U 6.000 com mais de 60 dias de atraso. Quer ver as opções para regularizar?"},
      {"who": "cliente", "text": "Oi, quero. Agora não consigo pagar tudo de uma vez."},
      {"who": "ia", "text": "Sem problema. Posso oferecer: 1) Pagar hoje $U 5.700 (5% de desconto), ou 2) 3 parcelas de $U 1.900 sem juros. Qual prefere?"},
      {"who": "cliente", "text": "As 3 parcelas, por favor."},
      {"who": "ia", "text": "Perfeito ✓ Segue o link de pagamento da primeira parcela: kobra.pay/ab12c9 — vence em 5 dias."},
      {"who": "cliente", "text": "Pronto, muito obrigado."}
    ],
    "ui": {
      "etiqueta_ia": "MV Kobra AI (voz)",
      "etiqueta_cliente": "Cliente",
      "en_curso_voz": "Chamada em andamento (voz real)…",
      "en_curso_nav": "Chamada em andamento (com voz)…",
      "en_curso": "Chamada em andamento…",
      "detenida": "⏹ Interrompida",
      "finalizada": "✓ Chamada finalizada · Duração 00:42 · Acordo de pagamento em 3 parcelas · sincronizado ao ERP",
      "idioma": "Idioma",
      "badge": "Cobranças Inteligentes",
      "header_sub": "ProbPago · Agente IA Negociador · Priorização por valor esperado de recuperação",
      "cinta": "Demo pública · dados sintéticos · ver planos",
      "pie": "MV Kobra AI · Plataforma de Cobranças Inteligentes · Demo com dados sintéticos (Uruguai). Sem nomes de clientes.",
      "f_segmento": "Segmento",
      "f_producto": "Produto",
      "f_tramo_mora": "Faixa de atraso",
      "f_propension": "Propensão",
      "f_departamento": "Departamento",
      "f_todos": "Todos",
      "f_prob_min": "ProbPago mínima:",
      "prop_Alta": "Alta",
      "prop_Media": "Média",
      "prop_Baja": "Baixa",
      "kpi_deudores": "Devedores",
      "kpi_cartera": "Carteira (UYU)",
      "kpi_recupero": "Recuperação esp. ({p}%)",
      "kpi_probpago": "ProbPago médio",
      "kpi_mora": "Atraso médio",
      "kpi_riesgo": "Carteira em risco",
      "dias": "dias",
      "g_tramo": "Carteira vs. recuperação esperada por faixa de atraso (M$U)",
      "g_prop": "Distribuição por propensão de pagamento",
      "g_seg": "Recuperação esperada por segmento (UYU)",
      "g_est": "Recuperação esperada por estratégia (UYU)",
      "ds_cartera": "Carteira",
      "ds_recupero_esp": "Recuperação esperada",
      "ds_recupero": "Recuperação",
      "t_titulo": "Carteira priorizada",
      "btn_csv": "Exportar CSV",
      "btn_excel": "Exportar Excel",
      "th_num": "#",
      "th_id": "ID",
      "th_segmento": "Segmento",
      "th_producto": "Produto",
      "th_depto": "Depto",
      "th_tramo": "Faixa",
      "th_monto": "Valor",
      "th_probpago": "ProbPago",
      "th_prop": "Prop.",
      "th_estrategia": "Estratégia",
      "th_desc": "Desc.",
      "th_canal": "Canal",
      "th_recupero": "Recup. esp.",
      "t_info": "{n} registros filtrados · mostrando top 300 por prioridade",
      "mc_titulo": "Teste com a sua carteira",
      "mc_texto": "Envie um CSV anonimizado —500 contas bastam— e veja o scoring rodando sobre os <b>seus</b> números. <b>O arquivo não sai do seu navegador</b>: é lido e pontuado aqui, não sobe para nenhum servidor. É o mesmo modelo que você vê acima, não uma versão de demonstração: os coeficientes saem do <code>.joblib</code> treinado.",
      "mc_elegir": "Escolher CSV",
      "mc_bajar": "⬇ Baixar um CSV de exemplo (500 contas)",
      "mc_leyendo": "Lendo {archivo}…",
      "mc_pesado": "Esse arquivo tem {mb} MB. Tente uma amostra de alguns milhares de linhas: para ver o scoring basta.",
      "mc_no_lee": "Não consegui ler o arquivo.",
      "mc_no_modelo": "Não consegui carregar o modelo ({e}). Recarregue a página.",
      "mc_sin_filas": "O arquivo não tem linhas de dados. Ficou só o cabeçalho?",
      "mc_faltan": "<b>Faltam {n} coluna(s) no arquivo.</b><br>O modelo precisa de: <code>{pedidas}</code>.<br>Não encontrei: <code>{faltan}</code>.<br>Baixe o CSV de exemplo acima para ver o formato exato — os nomes não diferenciam maiúsculas.",
      "mc_k_cuentas": "Contas pontuadas",
      "mc_k_prob": "ProbPago médio",
      "mc_k_recupero": "Recuperação esperada",
      "mc_k_altabaja": "Alta / baixa propensão",
      "mc_resumen": "{archivo} · {n} linhas em {ms} ms, no seu navegador. Carteira {cartera}.",
      "mc_top": "Top 15 por valor esperado de recuperação",
      "mc_th_cuenta": "Conta",
      "mc_th_monto": "Valor",
      "mc_th_recupero": "Recuperação esperada",
      "mc_th_prop": "Propensão",
      "mc_pie": "O modelo foi treinado com dados <b>sintéticos</b>: isto mostra a mecânica do scoring e da priorização. O desempenho real se mede retreinando com o seu histórico de pagamentos.",
      "v_titulo": "Agente IA por voz",
      "v_sub": "É assim que a MV Kobra AI liga e negocia por telefone, com voz sintetizada ao vivo (aumente o volume).",
      "v_btn": "▶ Reproduzir chamada de exemplo (com voz)",
      "v_stop": "⏹ Parar",
      "w_titulo": "Negociador por WhatsApp",
      "w_sub": "O mesmo agente fecha por chat, envia o link de pagamento e registra tudo sozinho.",
      "w_btn": "▶ Reproduzir conversa de exemplo",
      "w_escribiendo": "Digitando…",
      "c_titulo": "Copiloto de Negociação",
      "c_hint": "Cole uma conversa (WhatsApp ou transcrição). Analise <b>offline</b> no seu navegador, ou com <b>IA ao vivo</b> (motor neural real).",
      "c_btn_offline": "⚡ Analisar offline",
      "c_btn_ia": "Analisar com IA ao vivo",
      "c_sentimiento": "Sentimento do cliente turno a turno",
      "c_emociones": "Emoções:",
      "c_tecnicas": "Técnicas do agente:",
      "c_k_calidad": "Qualidade da gestão",
      "c_k_clima": "Clima do cliente",
      "c_k_emocion": "Emoção dominante",
      "c_k_tecnicas": "Técnicas usadas",
      "c_proxima": "Próxima frase sugerida",
      "c_turnos": "{n} turnos analisados",
      "c_pega": "Cole uma conversa.",
      "c_pega_primero": "Cole uma conversa primeiro.",
      "ia_consultando": "Consultando a IA…",
      "ia_titulo": "Análise de IA (ao vivo)",
      "ia_temp": "Temperatura do cliente",
      "ia_tecnicas": "Técnicas detectadas:",
      "ia_jugada": "Próxima jogada:",
      "ia_guion": "Roteiro sugerido:",
      "ia_nokey": "A IA ao vivo ainda não está configurada (falta a API key no servidor).",
      "ia_limit": "As demos gratuitas de IA ao vivo acabaram. Escreva para vieraschiavi@gmail.com para ampliar.",
      "ia_error": "Não foi possível analisar ao vivo ({e}).",
      "ia_sin_conexion": "Sem conexão com a IA: {e}",
      "ia_restantes": "IA ao vivo: restam {n} demos gratuitas (global)",
      "e_titulo": "Resultados enviados ao seu ERP",
      "e_sub": "Cada atendimento fechado (voz, WhatsApp ou copiloto) se sincroniza sozinho com o seu ERP ou banco de dados — por API REST, SQL ou arquivo. É assim que aparece do outro lado:",
      "e_evolucion": "Evolução da recuperação (últimos 30 dias)",
      "e_mismo_dato": "O mesmo dado que o seu ERP recebe via API/SQL",
      "e_k_cerradas": "Atendimentos fechados",
      "e_k_sync": "Sincronizadas ao ERP",
      "e_k_pend": "Pendentes de sync",
      "e_k_recuperado": "Recuperado (30 dias)",
      "e_ds_recuperado": "Recuperado (UYU)",
      "e_th_fecha": "Data",
      "e_th_cliente": "Cliente",
      "e_th_canal": "Canal",
      "e_th_resultado": "Resultado",
      "e_th_monto": "Valor",
      "e_th_estado": "Status ERP",
      "e_sincronizado": "Sincronizado",
      "e_pendiente": "Pendente",
      "e_r_promesa": "Promessa de pagamento",
      "e_r_acuerdo": "Acordo parcelado",
      "e_r_pago": "Pagamento total",
      "e_r_sin_contacto": "Sem contato",
      "e_c_voz": "Voz IA",
      "e_c_whatsapp": "WhatsApp",
      "e_c_copiloto": "Copiloto",
      "cop_enojo_t": "Cliente irritado",
      "cop_enojo_d": "Diminua o ritmo, valide o incômodo ANTES de oferecer. Evite se justificar.",
      "cop_frustracion_t": "Frustração",
      "cop_frustracion_d": "Reconheça o histórico e ofereça algo concreto e diferente do anterior.",
      "cop_ansiedad_t": "Ansiedade",
      "cop_ansiedad_d": "Transmita calma e passos curtos e claros: 'vamos fazer uma coisa só hoje'.",
      "cop_dificultad_t": "Dificuldade financeira",
      "cop_dificultad_d": "Priorize parcelamento ou desconto; não pressione pelo pagamento total.",
      "cop_compra_t": "Sinal de compra",
      "cop_compra_d": "Clima favorável: FECHE agora com data e meio de pagamento.",
      "cop_objecion_t": "Objeção ativa",
      "cop_objecion_d": "Não rebata de frente: 'que parte complica para você?' e ofereça 2 alternativas.",
      "cop_alta_t": "Alta propensão",
      "cop_alta_d": "Vise o pagamento total ou uma entrada forte; pouco ou nenhum desconto.",
      "cop_baja_t": "Baixa propensão",
      "cop_baja_d": "Garanta QUALQUER pagamento: libere desconto/plano longo e compromisso por escrito.",
      "cop_estrategia_t": "Estratégia sugerida",
      "cop_estrategia_d": "Roteiro recomendado pela MV Kobra AI: «{e}».",
      "cop_ok_t": "Tudo em ordem",
      "cop_ok_d": "Mantenha o tom e avance para o fechamento com uma proposta concreta.",
      "cop_next_cierre": "Perfeito, vamos combinar: envio agora o link de pagamento e o comprovante chega para você. Fica bom assim?",
      "cop_next_enojo": "Entendo o seu incômodo e quero resolver hoje mesmo. Proponho uma opção sob medida, vamos ver?",
      "cop_next_dificultad": "Sem problema, vamos buscar algo compatível com a sua situação. Quanto conseguiria pagar este mês?",
      "cop_next_default": "Que tal dividirmos em parcelas confortáveis e começarmos com uma hoje?",
      "clima_positivo": "positivo",
      "clima_neutro": "neutro",
      "clima_negativo": "negativo",
      "emo_enojo": "raiva",
      "emo_frustracion": "frustração",
      "emo_ansiedad": "ansiedade",
      "emo_dificultad_economica": "dificuldade financeira",
      "emo_intencion_pago": "intenção de pagamento",
      "emo_objecion": "objeção",
      "d_Corporativo": "Corporativo",
      "d_Pyme": "PME",
      "d_Retail": "Varejo",
      "d_Crédito automotor": "Crédito automotivo",
      "d_Cuenta corriente": "Conta corrente",
      "d_Financiación retail": "Financiamento varejo",
      "d_Microcrédito": "Microcrédito",
      "d_Préstamo personal": "Empréstimo pessoal",
      "d_Tarjeta de crédito": "Cartão de crédito",
      "d_Derivación a gestión especializada": "Encaminhamento para gestão especializada",
      "d_Descuento máximo / cierre de cuenta": "Desconto máximo / encerramento da conta",
      "d_Pago total facilitado": "Pagamento total facilitado",
      "d_Plan de cuotas": "Plano de parcelas",
      "d_Plan de cuotas + quita moderada": "Plano de parcelas + desconto moderado",
      "d_Quita agresiva por pago único": "Desconto agressivo por pagamento único",
      "d_Recordatorio suave": "Lembrete leve",
      "d_Email": "E-mail",
      "d_Llamada": "Ligação",
      "d_SMS": "SMS",
      "d_WhatsApp": "WhatsApp",
      "modelo_logistica": "Regressão Logística (selecionada por CV + calibrada)",
      "lift_decil": "decil 10",
      "e_doc_titulo": "MV Kobra AI · Resultados enviados ao ERP"
    }
  },
  "en": {
    "nombre": "English",
    "llamada": [
      {"who": "ia", "text": "Good morning, this is MV Kobra AI calling on behalf of your financial institution. Am I speaking with John Parker?"},
      {"who": "cliente", "text": "Yes, speaking."},
      {"who": "ia", "text": "I'm calling about an outstanding balance of 6,000 pesos, more than 60 days overdue. Can we go over the available payment options together?"},
      {"who": "cliente", "text": "Honestly, I can't pay it all at once right now, money is tight."},
      {"who": "ia", "text": "I understand. I can offer you a 5% discount if you settle today, bringing it to 5,700 pesos, or split it into 3 instalments of 1,900 pesos at no extra cost. Which one works better for you?"},
      {"who": "cliente", "text": "I'd rather do the 3 instalments."},
      {"who": "ia", "text": "Perfect. I'll send you the payment link for the first instalment on WhatsApp, due in 5 days. Can you confirm this number?"},
      {"who": "cliente", "text": "Yes, confirmed."},
      {"who": "ia", "text": "Excellent. The payment plan in 3 instalments has been recorded. Thank you for your time, have a good day."}
    ],
    "whatsapp": [
      {"who": "ia", "text": "Hi John I'm the collections assistant from your financial institution. You have an outstanding balance of $U 6,000, more than 60 days overdue. Would you like to look at the options to settle it?"},
      {"who": "cliente", "text": "Hi, yes. I can't pay it all at once right now."},
      {"who": "ia", "text": "No problem. I can offer you: 1) Pay $U 5,700 today (5% discount), or 2) 3 instalments of $U 1,900 at no extra cost. Which do you prefer?"},
      {"who": "cliente", "text": "The 3 instalments, please."},
      {"who": "ia", "text": "Perfect ✓ Here's the payment link for the first instalment: kobra.pay/ab12c9 — due in 5 days."},
      {"who": "cliente", "text": "Got it, thank you."}
    ],
    "ui": {
      "etiqueta_ia": "MV Kobra AI (voice)",
      "etiqueta_cliente": "Customer",
      "en_curso_voz": "Call in progress (real voice)…",
      "en_curso_nav": "Call in progress (with voice)…",
      "en_curso": "Call in progress…",
      "detenida": "⏹ Stopped",
      "finalizada": "✓ Call ended · Duration 00:42 · Payment plan in 3 instalments · synced to the ERP",
      "idioma": "Language",
      "badge": "Smart Collections",
      "header_sub": "ProbPago · AI Negotiator Agent · Prioritisation by expected recovery value",
      "cinta": "Public demo · synthetic data · see plans",
      "pie": "MV Kobra AI · Smart Collections Platform · Demo on synthetic data (Uruguay). No customer names.",
      "f_segmento": "Segment",
      "f_producto": "Product",
      "f_tramo_mora": "Days-past-due bucket",
      "f_propension": "Propensity",
      "f_departamento": "Region",
      "f_todos": "All",
      "f_prob_min": "Minimum ProbPago:",
      "prop_Alta": "High",
      "prop_Media": "Medium",
      "prop_Baja": "Low",
      "kpi_deudores": "Debtors",
      "kpi_cartera": "Portfolio (UYU)",
      "kpi_recupero": "Exp. recovery ({p}%)",
      "kpi_probpago": "Average ProbPago",
      "kpi_mora": "Average days past due",
      "kpi_riesgo": "At-risk portfolio",
      "dias": "days",
      "g_tramo": "Portfolio vs. expected recovery by days-past-due bucket (M$U)",
      "g_prop": "Distribution by payment propensity",
      "g_seg": "Expected recovery by segment (UYU)",
      "g_est": "Expected recovery by strategy (UYU)",
      "ds_cartera": "Portfolio",
      "ds_recupero_esp": "Expected recovery",
      "ds_recupero": "Recovery",
      "t_titulo": "Prioritised portfolio",
      "btn_csv": "Export CSV",
      "btn_excel": "Export Excel",
      "th_num": "#",
      "th_id": "ID",
      "th_segmento": "Segment",
      "th_producto": "Product",
      "th_depto": "Region",
      "th_tramo": "Bucket",
      "th_monto": "Amount",
      "th_probpago": "ProbPago",
      "th_prop": "Prop.",
      "th_estrategia": "Strategy",
      "th_desc": "Disc.",
      "th_canal": "Channel",
      "th_recupero": "Exp. recovery",
      "t_info": "{n} filtered records · showing top 300 by priority",
      "mc_titulo": "Try it with your own portfolio",
      "mc_texto": "Upload an anonymised CSV —500 accounts is enough— and watch the scoring run on <b>your</b> numbers. <b>The file never leaves your browser</b>: it is parsed and scored right here, never uploaded. It is the same model you see above, not a demo version: the coefficients come from the trained <code>.joblib</code>.",
      "mc_elegir": "Choose CSV",
      "mc_bajar": "⬇ Download a sample CSV (500 accounts)",
      "mc_leyendo": "Reading {archivo}…",
      "mc_pesado": "That file is {mb} MB. Try a sample of a few thousand rows — that is plenty to see the scoring.",
      "mc_no_lee": "I could not read the file.",
      "mc_no_modelo": "I could not load the model ({e}). Please reload the page.",
      "mc_sin_filas": "The file has no data rows. Is it header-only?",
      "mc_faltan": "<b>The file is missing {n} column(s).</b><br>The model needs: <code>{pedidas}</code>.<br>Not found: <code>{faltan}</code>.<br>Download the sample CSV above to see the exact format — names are case-insensitive.",
      "mc_k_cuentas": "Accounts scored",
      "mc_k_prob": "Average ProbPago",
      "mc_k_recupero": "Expected recovery",
      "mc_k_altabaja": "High / low propensity",
      "mc_resumen": "{archivo} · {n} rows in {ms} ms, in your browser. Portfolio {cartera}.",
      "mc_top": "Top 15 by expected recovery value",
      "mc_th_cuenta": "Account",
      "mc_th_monto": "Amount",
      "mc_th_recupero": "Expected recovery",
      "mc_th_prop": "Propensity",
      "mc_pie": "The model is trained on <b>synthetic</b> data: this shows the mechanics of the scoring and the prioritisation. Real performance is measured by retraining on your own payment history.",
      "v_titulo": "AI voice agent",
      "v_sub": "This is how MV Kobra AI calls and negotiates over the phone, with live synthesised voice (turn the volume up).",
      "v_btn": "▶ Play sample call (with voice)",
      "v_stop": "⏹ Stop",
      "w_titulo": "WhatsApp negotiator",
      "w_sub": "The same agent closes over chat, sends the payment link and logs everything on its own.",
      "w_btn": "▶ Play sample conversation",
      "w_escribiendo": "Typing…",
      "c_titulo": "Negotiation copilot",
      "c_hint": "Paste a conversation (WhatsApp or a transcript). Analyse it <b>offline</b> in your browser, or with <b>live AI</b> (a real neural engine).",
      "c_btn_offline": "⚡ Analyse offline",
      "c_btn_ia": "Analyse with live AI",
      "c_sentimiento": "Customer sentiment turn by turn",
      "c_emociones": "Emotions:",
      "c_tecnicas": "Agent techniques:",
      "c_k_calidad": "Handling quality",
      "c_k_clima": "Customer mood",
      "c_k_emocion": "Dominant emotion",
      "c_k_tecnicas": "Techniques used",
      "c_proxima": "Suggested next line",
      "c_turnos": "{n} turns analysed",
      "c_pega": "Paste a conversation.",
      "c_pega_primero": "Paste a conversation first.",
      "ia_consultando": "Asking the AI…",
      "ia_titulo": "AI analysis (live)",
      "ia_temp": "Customer temperature",
      "ia_tecnicas": "Detected techniques:",
      "ia_jugada": "Next move:",
      "ia_guion": "Suggested script:",
      "ia_nokey": "Live AI is not configured yet (the server is missing the API key).",
      "ia_limit": "The free live-AI demos are used up. Write to vieraschiavi@gmail.com to extend them.",
      "ia_error": "Live analysis failed ({e}).",
      "ia_sin_conexion": "No connection to the AI: {e}",
      "ia_restantes": "Live AI: {n} free demos left (global)",
      "e_titulo": "Results pushed to your ERP",
      "e_sub": "Every closed interaction (voice, WhatsApp or copilot) syncs itself to your ERP or database — over REST API, SQL or file. This is how it looks on the other side:",
      "e_evolucion": "Recovery trend (last 30 days)",
      "e_mismo_dato": "The same data your ERP receives over API/SQL",
      "e_k_cerradas": "Interactions closed",
      "e_k_sync": "Synced to the ERP",
      "e_k_pend": "Pending sync",
      "e_k_recuperado": "Recovered (30 days)",
      "e_ds_recuperado": "Recovered (UYU)",
      "e_th_fecha": "Date",
      "e_th_cliente": "Customer",
      "e_th_canal": "Channel",
      "e_th_resultado": "Outcome",
      "e_th_monto": "Amount",
      "e_th_estado": "ERP status",
      "e_sincronizado": "Synced",
      "e_pendiente": "Pending",
      "e_r_promesa": "Promise to pay",
      "e_r_acuerdo": "Instalment agreement",
      "e_r_pago": "Paid in full",
      "e_r_sin_contacto": "No contact",
      "e_c_voz": "AI voice",
      "e_c_whatsapp": "WhatsApp",
      "e_c_copiloto": "Copilot",
      "cop_enojo_t": "Angry customer",
      "cop_enojo_d": "Slow down; acknowledge their frustration BEFORE offering anything. Don't justify.",
      "cop_frustracion_t": "Frustration",
      "cop_frustracion_d": "Acknowledge the history and offer something concrete and different from before.",
      "cop_ansiedad_t": "Anxiety",
      "cop_ansiedad_d": "Convey calm and short, clear steps: 'let's do just one thing today'.",
      "cop_dificultad_t": "Financial hardship",
      "cop_dificultad_d": "Favour an instalment plan or a write-off; don't push for payment in full.",
      "cop_compra_t": "Buying signal",
      "cop_compra_d": "Favourable mood: CLOSE now with a date and a payment method.",
      "cop_objecion_t": "Live objection",
      "cop_objecion_d": "Don't push back head-on: 'which part is the problem?' and offer 2 alternatives.",
      "cop_alta_t": "High propensity",
      "cop_alta_d": "Aim for payment in full or a strong first instalment; little or no write-off.",
      "cop_baja_t": "Low propensity",
      "cop_baja_d": "Secure ANY payment: allow a write-off or a long plan, and get it in writing.",
      "cop_estrategia_t": "Suggested strategy",
      "cop_estrategia_d": "Script recommended by MV Kobra AI: “{e}”.",
      "cop_ok_t": "All good",
      "cop_ok_d": "Keep the tone and move to the close with a concrete proposal.",
      "cop_next_cierre": "Great, let's set it up: I'll send the payment link now and you'll get the receipt. Does that work for you?",
      "cop_next_enojo": "I understand your frustration and I want to sort this out today. Let me propose an option tailored to you — shall we look at it?",
      "cop_next_dificultad": "No problem — let's find something that fits your situation. How much could you manage this month?",
      "cop_next_default": "How about we split it into comfortable instalments and start with one today?",
      "clima_positivo": "positive",
      "clima_neutro": "neutral",
      "clima_negativo": "negative",
      "emo_enojo": "anger",
      "emo_frustracion": "frustration",
      "emo_ansiedad": "anxiety",
      "emo_dificultad_economica": "financial hardship",
      "emo_intencion_pago": "intent to pay",
      "emo_objecion": "objection",
      "d_Corporativo": "Corporate",
      "d_Pyme": "SME",
      "d_Retail": "Retail",
      "d_Crédito automotor": "Auto loan",
      "d_Cuenta corriente": "Current account",
      "d_Financiación retail": "Retail finance",
      "d_Microcrédito": "Microloan",
      "d_Préstamo personal": "Personal loan",
      "d_Tarjeta de crédito": "Credit card",
      "d_Derivación a gestión especializada": "Escalate to a specialist team",
      "d_Descuento máximo / cierre de cuenta": "Maximum discount / close the account",
      "d_Pago total facilitado": "Assisted payment in full",
      "d_Plan de cuotas": "Instalment plan",
      "d_Plan de cuotas + quita moderada": "Instalment plan + moderate write-off",
      "d_Quita agresiva por pago único": "Aggressive write-off for a single payment",
      "d_Recordatorio suave": "Gentle reminder",
      "d_Email": "Email",
      "d_Llamada": "Call",
      "d_SMS": "SMS",
      "d_WhatsApp": "WhatsApp",
      "modelo_logistica": "Logistic Regression (selected by CV + calibrated)",
      "lift_decil": "decile 10",
      "e_doc_titulo": "MV Kobra AI · Results pushed to the ERP"
    }
  }
};

// Idioma activo del demo. Prioridad: ?lang= en la URL (sirve también offline,
// donde no hay localStorage compartido con el sitio) → lo que se eligió en la
// landing (mismo origen, misma clave) → el idioma del navegador → español.
window.IDIOMA_DEMO = (function () {
  var soportados = ['es', 'pt', 'en'];
  function normalizar(v) {
    if (!v) return null;
    v = String(v).toLowerCase().slice(0, 2);
    return soportados.indexOf(v) >= 0 ? v : null;
  }
  var url = null;
  try {
    url = normalizar(new URLSearchParams(window.location.search).get('lang'));
  } catch (e) { /* URLSearchParams falta en navegadores muy viejos */ }
  // /demo/en/ o /demo/pt/ como PATH: existen para que el preview social (que
  // no ejecuta este script) tenga metatags propios — ver
  // marketing/generar_paginas_idioma.py. Pesa más que lo guardado en
  // localStorage: llegar caminando el sitio a /demo/en/ es una señal más
  // fuerte que una preferencia vieja de una visita anterior.
  var ruta = null;
  try {
    ruta = normalizar((window.location.pathname.match(/^\/demo\/(en|pt)\//) || [])[1]);
  } catch (e) {}
  var guardado = null;
  try { guardado = normalizar(window.localStorage.getItem('kobra_lang')); } catch (e) {}
  var navegador = normalizar(navigator && navigator.language);
  return url || ruta || guardado || navegador || 'es';
})();

// Traductor de la interfaz. Vive acá y no en index.html porque `guiones.js` se
// carga en el <head>: así el idioma ya está resuelto cuando corre cualquier
// script de la página, incluido el que pinta el copiloto.
//
// `T('clave', {n: 5})` devuelve el texto del idioma activo con los {marcadores}
// reemplazados. Si a un idioma le falta una clave cae al español en vez de
// dejar el hueco en blanco: en un demo comercial, media pantalla vacía es peor
// que una etiqueta sin traducir.
window.T = function (clave, vars) {
  var d = window.GUIONES || {};
  var txt = ((d[window.IDIOMA_DEMO] || {}).ui || {})[clave];
  if (txt === undefined) txt = ((d.es || {}).ui || {})[clave];
  if (txt === undefined) return '';
  if (vars) {
    txt = txt.replace(/\{(\w+)\}/g, function (m, k) {
      return vars[k] === undefined ? m : String(vars[k]);
    });
  }
  return txt;
};

// Aplica las traducciones al HTML estático. `data-i18n` reemplaza el texto;
// `data-i18n-html` reemplaza el HTML —solo para las claves del diccionario, que
// es contenido propio del sitio, nunca datos de nadie—.
window.traducirDOM = function (raiz) {
  raiz = raiz || document;
  var t = raiz.querySelectorAll('[data-i18n]');
  for (var i = 0; i < t.length; i++) t[i].textContent = window.T(t[i].getAttribute('data-i18n'));
  var h = raiz.querySelectorAll('[data-i18n-html]');
  for (var j = 0; j < h.length; j++) h[j].innerHTML = window.T(h[j].getAttribute('data-i18n-html'));
  document.documentElement.lang = window.IDIOMA_DEMO;
};
