# © 2026 Martín Viera. Todos los derechos reservados.

"""
MV Kobra AI · La memoria técnica, en los tres formatos que se piden
====================================================================
HTML para mandar por mail o publicar, Word para que alguien lo edite y le
agregue lo suyo, PDF para imprimir y llevar a una reunión.

Los tres salen del MISMO catálogo (`kobra/memoria_tecnica.py`). No hay una
plantilla por formato con el texto adentro: eso garantiza que a los tres meses
el PDF diga una cosa y el HTML otra, y que nadie se entere hasta que un cliente
compare los dos.

Por qué los renderizadores están acá y no en el catálogo
--------------------------------------------------------
El catálogo lo leen la API, la pantalla y los tests; los renderizadores solo
los usa el export. Separarlos evita que `kobra/memoria_tecnica.py` arrastre
`fpdf` y `python-docx` cada vez que la pantalla pide la lista — que es el 99%
de las veces.
"""
from __future__ import annotations

import html
import io

from kobra import memoria_tecnica as mt

# El envoltorio del documento —título, bajada, nombre de cada bloque y el pie—
# es lo ÚNICO que no sale del catálogo de etapas, así que vive acá. Si viviera
# en los JSON de etapas habría que repetirlo trece veces por idioma.
_CHROME = {
    "es": {
        "titulo": "MV Kobra AI · Memoria técnica del pipeline",
        "bajada": ("Qué hace el programa, en orden, contado dos veces: una "
                   "para quien lee el código y otra para quien firma la compra."),
        "tecnico": "Técnico", "criollo": "En criollo",
        "por_que": "Por qué se hizo",
        "repercusion": "Cómo repercute aguas abajo",
        "limites": "Qué NO hace",
        "entra": "Entra", "sale": "Sale", "donde": "Dónde vive",
        "etapa_de": "Etapa {n} de {total}",
        "pie": ("Documento generado por el propio programa a partir de "
                "kobra/memoria_tecnica.py: describe el pipeline tal como está "
                "implementado."),
        "pie_demo": (" Los datos de esta instalación son SINTÉTICOS y las "
                     "cifras de impacto son ILUSTRATIVAS, no resultados "
                     "medidos en producción."),
    },
    "en": {
        "titulo": "MV Kobra AI · Technical memo on the pipeline",
        "bajada": ("What the program does, in order, told twice: once for "
                   "whoever reads the code and once for whoever signs the "
                   "purchase."),
        "tecnico": "Technical", "criollo": "In plain terms",
        "por_que": "Why it was built",
        "repercusion": "How it ripples downstream",
        "limites": "What it does NOT do",
        "entra": "In", "sale": "Out", "donde": "Where it lives",
        "etapa_de": "Stage {n} of {total}",
        "pie": ("Document generated by the program itself from "
                "kobra/memoria_tecnica.py: it describes the pipeline as it is "
                "implemented."),
        "pie_demo": (" The data in this installation is SYNTHETIC and the "
                     "impact figures are ILLUSTRATIVE, not results measured "
                     "in production."),
    },
    "pt": {
        "titulo": "MV Kobra AI · Memória técnica do pipeline",
        "bajada": ("O que o programa faz, em ordem, contado duas vezes: uma "
                   "para quem lê o código e outra para quem assina a compra."),
        "tecnico": "Técnico", "criollo": "Em linguagem simples",
        "por_que": "Por que foi feito",
        "repercusion": "Como repercute adiante",
        "limites": "O que NÃO faz",
        "entra": "Entra", "sale": "Sai", "donde": "Onde vive",
        "etapa_de": "Etapa {n} de {total}",
        "pie": ("Documento gerado pelo próprio programa a partir de "
                "kobra/memoria_tecnica.py: descreve o pipeline tal como está "
                "implementado."),
        "pie_demo": (" Os dados desta instalação são SINTÉTICOS e os números "
                     "de impacto são ILUSTRATIVOS, não resultados medidos em "
                     "produção."),
    },
}


def _chrome(idioma: str) -> dict:
    return _CHROME[mt.normalizar(idioma)]


def _pie(idioma: str, datos_demo: bool) -> str:
    """La misma aclaración en los tres formatos y en los tres idiomas.

    No es un disclaimer de trámite: la demo corre sobre datos sintéticos y las
    cifras de impacto son ilustrativas. Un documento técnico que no lo diga se
    lee como si los números fueran de un cliente real.
    """
    c = _chrome(idioma)
    return c["pie"] + (c["pie_demo"] if datos_demo else "")


def _bloques(et, c) -> list[tuple[str, str, str]]:
    """(etiqueta, texto, clase) de cada bloque de una etapa, en orden.

    Uno solo para los tres formatos: agregar un bloque en el HTML y olvidarlo
    en el PDF es exactamente la divergencia que este módulo existe para
    evitar.
    """
    orden = ("tecnico", "criollo", "por_que", "repercusion", "limites")
    return [(c[k], getattr(et, k), k) for k in orden if getattr(et, k)]


# --- HTML -------------------------------------------------------------------
def como_html(datos_demo: bool = True, idioma: str = "es") -> str:
    """Un solo archivo, sin CSS externo ni JavaScript.

    Autocontenido a propósito: este HTML se manda adjunto por mail y se abre
    con doble clic desde el Escritorio. Una hoja de estilos por CDN lo deja sin
    formato en la mitad de esos casos, y un `<script>` hace que algunos
    clientes de correo lo bloqueen entero.
    """
    e_ = html.escape
    lang = mt.normalizar(idioma)
    c = _chrome(lang)
    etapas = mt.etapas(lang)
    partes = [
        "<!doctype html>", f'<html lang="{lang}"><head><meta charset="utf-8">',
        f"<title>{e_(c['titulo'])}</title>",
        "<style>",
        "body{font:15px/1.6 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;",
        "     max-width:52rem;margin:2rem auto;padding:0 1.2rem;color:#16202b}",
        "h1{font-size:1.7rem;margin:0 0 .3rem}",
        ".bajada{color:#5b6b7c;margin:0 0 2rem}",
        "article{border-top:1px solid #dfe6ee;padding:1.4rem 0}",
        "h2{font-size:1.15rem;margin:0 0 .1rem}",
        ".orden{color:#8a99a8;font-variant-numeric:tabular-nums;font-size:.85rem}",
        "dt{font-weight:600;margin-top:.9rem;font-size:.82rem;",
        "   text-transform:uppercase;letter-spacing:.04em;color:#41566b}",
        "dd{margin:.25rem 0 0}",
        ".criollo{background:#f4f8fc;border-left:3px solid #2f6fb0;",
        "         padding:.7rem .9rem;border-radius:0 4px 4px 0}",
        ".limites{color:#7a4a1e}",
        ".meta{margin-top:1rem;font-size:.82rem;color:#6b7b8b}",
        "code{background:#eef3f8;padding:.1rem .3rem;border-radius:3px;",
        "     font-size:.85em}",
        "footer{border-top:1px solid #dfe6ee;margin-top:2rem;padding-top:1rem;",
        "       font-size:.82rem;color:#6b7b8b}",
        "@media print{body{max-width:none;margin:0}article{break-inside:avoid}}",
        "</style></head><body>",
        f"<h1>{e_(c['titulo'])}</h1>",
        f'<p class="bajada">{e_(c["bajada"])}</p>',
    ]
    for et in etapas:
        partes += [
            "<article>",
            '<div class="orden">'
            + e_(c["etapa_de"].format(n=et.orden, total=len(etapas)))
            + "</div>",
            f"<h2>{e_(et.titulo)}</h2>", "<dl>",
        ]
        for etiqueta, texto, clave in _bloques(et, c):
            clase = f' class="{clave}"' if clave in ("criollo", "limites") else ""
            partes.append(f"<dt>{e_(etiqueta)}</dt><dd{clase}>{e_(texto)}</dd>")
        partes += [
            "</dl>", '<p class="meta">',
            f"<b>{e_(c['entra'])}:</b> {e_(et.entradas)}<br>",
            f"<b>{e_(c['sale'])}:</b> {e_(et.salidas)}<br>",
            f"<b>{e_(c['donde'])}:</b> "
            + " · ".join(f"<code>{e_(m)}</code>" for m in et.modulos),
            "</p></article>",
        ]
    partes += [f"<footer>{e_(_pie(lang, datos_demo))}</footer>",
               "</body></html>"]
    return "\n".join(partes)


# --- Word -------------------------------------------------------------------
def como_docx(datos_demo: bool = True, idioma: str = "es") -> bytes:
    """`.docx` de verdad, no un HTML con extensión cambiada.

    El atajo conocido es servir HTML con `Content-Type: application/msword`:
    Word lo abre, pero el archivo miente sobre lo que es, se rompe al editarlo
    en Google Docs o LibreOffice, y deja al que lo recibe explicando por qué su
    editor no lo toma. `python-docx` cuesta 250 KB en el instalador y devuelve
    un documento que cualquier editor entiende.
    """
    from docx import Document
    from docx.shared import Pt

    lang = mt.normalizar(idioma)
    c = _chrome(lang)
    doc = Document()
    doc.add_heading(c["titulo"], level=0)
    doc.add_paragraph(c["bajada"])

    for et in mt.etapas(lang):
        doc.add_heading(f"{et.orden}. {et.titulo}", level=1)
        for etiqueta, texto, _ in _bloques(et, c):
            p = doc.add_paragraph()
            r = p.add_run(f"{etiqueta}: ")
            r.bold = True
            p.add_run(texto)
        meta = doc.add_paragraph()
        meta.add_run(f"{c['entra']}: {et.entradas}\n{c['sale']}: {et.salidas}\n"
                     f"{c['donde']}: {' · '.join(et.modulos)}")
        for run in meta.runs:
            run.font.size = Pt(9)

    doc.add_page_break()
    pie = doc.add_paragraph(_pie(lang, datos_demo))
    for run in pie.runs:
        run.font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# --- PDF --------------------------------------------------------------------
def _latin1(texto: str) -> str:
    """FPDF con las fuentes del núcleo solo escribe latin-1.

    Un carácter fuera de ese rango —una comilla tipográfica pegada desde Word,
    un guion largo— hace explotar la generación entera con
    `UnicodeEncodeError`. Se reemplazan los sospechosos habituales por su
    equivalente y el resto se degrada, en vez de perder el PDF completo por un
    carácter. Los acentos del castellano y del portugués SÍ están en latin-1 y
    se conservan.
    """
    reemplazos = {"—": "-", "–": "-", "“": '"', "”": '"', "‘": "'",
                  "’": "'", "…": "...", "·": "-", "→": "->", "≥": ">=",
                  "≤": "<=", "×": "x"}
    for viejo, nuevo in reemplazos.items():
        texto = texto.replace(viejo, nuevo)
    return texto.encode("latin-1", "replace").decode("latin-1")


def como_pdf(datos_demo: bool = True, idioma: str = "es") -> bytes:
    """Mismo contenido, para imprimir y llevar."""
    from fpdf import FPDF

    lang = mt.normalizar(idioma)
    c = _chrome(lang)
    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()
    ancho = pdf.w - pdf.l_margin - pdf.r_margin

    pdf.set_font("Helvetica", "B", 16)
    pdf.multi_cell(ancho, 8, _latin1(c["titulo"]))
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(90, 105, 120)
    pdf.multi_cell(ancho, 5, _latin1(c["bajada"]))
    pdf.set_text_color(20, 30, 40)
    pdf.ln(3)

    for et in mt.etapas(lang):
        pdf.set_font("Helvetica", "B", 12)
        pdf.multi_cell(ancho, 6, _latin1(f"{et.orden}. {et.titulo}"))
        for etiqueta, texto, _ in _bloques(et, c):
            pdf.set_font("Helvetica", "B", 9)
            pdf.multi_cell(ancho, 4.6, _latin1(etiqueta))
            pdf.set_font("Helvetica", "", 9.5)
            pdf.multi_cell(ancho, 4.6, _latin1(texto))
            pdf.ln(0.8)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(105, 120, 135)
        pdf.multi_cell(ancho, 4, _latin1(
            f"{c['entra']}: {et.entradas} | {c['sale']}: {et.salidas} | "
            f"{c['donde']}: {' · '.join(et.modulos)}"))
        pdf.set_text_color(20, 30, 40)
        pdf.ln(3)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(105, 120, 135)
    pdf.multi_cell(ancho, 4, _latin1(_pie(lang, datos_demo)))

    return bytes(pdf.output())
